### ISSUE TITLE
Website roadmap

### ISSUE THREAD

**Issue by kunal-kushwaha** [WeMakeDevs/wemakedevs#23]
- [x] Main page
  - [x] About
  - [x] Sections
    - [x] Courses
    - [x] Events
    - [x] Mentorship
    - [x] Podcasts - just redirect to Open Source Cafe
    - [x] Blogs - just redirect to Hashnode
- [ ] Dedicated pages
  - [x] Courses
    - [x] Cards for courses
    - [ ] Each card will have a separate page like we did in Kartra
  - [ ] Events
    - [x] Cards for current and previous events
    - [ ] Stats
    - [ ] Each card might have separate page like Hackathon, Hashnode challenges
  - [x] Mentorship
    - [x] Just an intro page and direct it to GitHub
  - [ ] Testimonials
    - [ ] Kunal to give statements from organisations we have collaborate with for events and we will put testimonials here.
    - [ ] Also a section for individual student testimonials.

**Comment by CoffeeGeek101** [comment]
Hey, a GitHub newbie here. I have been honing my Front-End skills lately and I wonder if I can contribute building the Mentorship Page as to get my hands on some real life project.
